[project]
name = "crawlers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "crawl4ai>=0.6.3",
    "dynaconf>=3.2.11",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
