name: "acrc"
start_page: "https://www.acrcimoveis.com.br/imoveis/pagina-1"
allowed_domains:
  - acrcimoveis.com.br
blocked_domains:
  - adm055940.superlogica.net

filter_patterns:
  - "https://www.acrcimoveis.com.br/imoveis/pagina-*"

target_elements:
  - div.dados_imovel
  - div.descricao_imovel
  - div.todos_itens

# depth para todas as páginas math.floor(total_pages / 3)
max_depth: 1
items_url_pattern: '^https:\/\/www\.acrcimoveis\.com\.br\/(comprar|imoveis|alugar)\/[a-z]{2}\/[a-z\-]+\/[a-z\-]+\/[a-z\-]+\/\d+\/?$'