browser:
  agent: CasIA/1.0
llm:
  api_token: "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"
#  "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"
  provider: "openrouter/google/gemini-2.0-flash-exp:free"
  prompt: |
    Você é um especialista em análise de imóveis no mercado brasileiro.
    Sua tarefa é extrair informações estruturadas a respeito de imóveis.
    Se um atributo do schema não for mencionado ou não puder ser determinado, defina-o como null.
    Para campos booleanos (como mobiliado, ar_condicionado, etc.), retorne true apenas se
    mencionado explicitamente ou claramente inferido do contexto, caso contrário retorne false.
    Informações relevantes ao domínio que não estão no schema devem ser incluidas nos atributos.
    Não tente adivinhar informações que não estejam explícitas ou fortemente implicadas no texto. 

table_name: "property"

s3:
  bucket_name: "casia-imobiliarias-crawler"
