name: "zelt"
start_page: "https://www.zelt.com.br/imoveis?page=1"
next_pages:
  pattern: "https://www.zelt.com.br/imoveis?page={{ page }}"
  max_pages: 2

allowed_domains:
  - zelt.com.br

filter_patterns:
  - "https://www.zelt.com.br/imoveis?page=*"

target_elements:
  - div.container
  - div.top-listing

items_url_pattern: '^https:\/\/www\.zelt\.com\.br\/(empreendimento|imovel)\/.*\/\d+-[A-Z]+$'
